name: acoder # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Increase your programming speed with an AI assistant that generates code # 79 char long summary
description: |
  Acoder is a console application that generates code in programming languages, using artificial intelligence (powered by OpenAI GPT-3). The user provides a task description, file/files for Acoder to change, file/files for Acoder to look at (in order to know the context) and Acoder proposes changes in the code to accomplish the described task.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  acoder:
    plugin: python
    source: .

apps:
  acoder:
    command: bin/main.py
