error_messages = {
    'Task unsafe': """The task can be unsafe. We don't allow to generate long text using Acoder (e.g. generating articles or blog posts) because it can have negative social implications. Acoder classified your task as unsafe. If you tried to generate text, then that's why. However, Acoder sometimes makes mistakes and flags tasks that are safe as unsafe. If you didn't try to generate text, then Acoder probably categorized the task incorrectly. We apologize for causing pain in the ass and we will hopefully improve that in the future.
    
What to do now - possible options:
1. If you didn't try to generate text and you know what in your task description might have caused this error, then you might try to rephrase the task description so that it doesn't suggest to generate text and then try again.
2. Do the task by yourself.
""",
    'Input too long': """The cummulative length of the files that you have included is too long.
    
What to do now - possible options:
1. Include less files below 'Change' or 'Look'.
2. Do the task by yourself.""",
    'Output too long': """The cumulative length of the files that you have included and the changes generated by Acoder is too long.
    
What to do now - possible options:
1. Include less files below 'Change' or 'Look'.
2. Do the task by yourself.
""",
    'Content filter triggered': """The sensitive content filter has been triggered.
    
What to do now - possible options:
1. If you know what could cause that, then change the task so that Acoder doesn't have to generate sensitive content.
2. Do the task by yourself.""",
    'File not found': """One of the files does not exist.
    
What to do now - possible options:
1. Open the task file and ensure that all files listed under 'Look' exist.
""",
    'Server not found': """The application has failed to connect to the Acoder server.

What do do now - possible options:
1. Ensure that your internet connection is working.
2. Ensure that you are using the latest version of Acoder.
""",
    'Functions not implemented': """Specifying functions feature is not fully implemented yet."""
}
