error_messages = {
    'Task unsafe': """The task can be unsafe. We don't allow to generate long text using Acoder (e.g. generating articles or blog posts) because it can have negative social implications. Acoder classified your task as unsafe. If you tried to generate text, then that's why. However, Acoder sometimes makes mistakes and flags tasks that are safe as unsafe. If you didn't try to generate text, then Acoder probably categorized the task incorrectly. We apologize for causing pain in the ass and we will hopefully improve that in the future.
    
What you can do now - possible options:
1. If you didn't try to generate text and you know what in your task description might have caused this error, then you might try to rephrase the task description so that it doesn't suggest to generate text and then try again.
2. Do the task by yourself.
""",
    'Input too long': """The cummulative length of the files that you have included is too long.
    
What you can do now - possible options:
1. Include less files below 'Change' or 'Look'.
2. Do the task by yourself.""",
    'Output too long': """The cumulative length of the files that you have included and the changes generated by Acoder is too long.
    
What you can do now - possible options:
1. Include less files below 'Change' or 'Look'.
2. Do the task by yourself.
""",
    'Content filter triggered': """The sensitive content filter has been triggered.
    
What you can do now - possible options:
1. If you know what could cause that, then change the task so that Acoder doesn't have to generate sensitive content.
2. Do the task by yourself.""",
    'File not found': """One of the files does not exist.
    
What you can do now - possible options:
1. Ensure that the task with task description exists. If you didn't pass 'file_path' as argument of the command, then it will use 'task.md' file name by default.
2. Open the task file and ensure that all files listed under 'Look' exist.
""",
    'Server not found': """The application has failed to connect to the Acoder server.

What do do now - possible options:
1. Ensure that your internet connection is working.
2. Ensure that you are using the latest version of Acoder.
""",
    'Functions not implemented': """Specifying functions feature is not fully implemented yet.""",
    'Unexpected error': """There has been an unexpected error.
    
What you can do now - possible options:
1. Try again now.
2. Try again later.
3. Do the task by yourself.
""",
    'API key missing': """API key has not been configured.

What you can do now - possible options:
1. Before you can use Acoder, you need to sign up on the Acoder website. After signing up (or signing in), you will see your API key. Then, you need to configure Acoder by running: `acoder configure <you API key here>`. After you've done this, you will be able to use Acoder.""",
    'Invalid API key': """API key is invalid.

It might be because you've made a mistake when configuring it, possibly you've accidentally copied only part of the API key instead of the entire API key.

What you can do now - possible options:
1. Go to the Acoder website. Sign in and go to the "Dashboard" page. Copy the API key and run `acoder configure <you API key here>`.""",
    'Task file missing description': """The task file is missing the description of the task.
    
What you can do now - possible options:
1. Open the task file and ensure that there is a part like this in it: '## Description'.""",
    'Task file missing change': """The task file is missing the paths to the files that Acoder needs to change/create.

What you can do now - possible options:
1. Open the task file and ensure that there is a part like this in it: '## Change'.""",
    'Timeout': """We were waiting and waiting and haven't got any response from Acoder. Perhaps, Acoder is on a lunchbreak right now.

What you can do now - possible options:
1. Try again now.
2. Try again later.
3. Try and make the task simpler so that it takes less time for Acoder to return the response.
4. Do the task by yourself."""
}
